### ISSUE TITLE
$HOME/.local/share/kactivitymanagerd/activities is assumed to exist

### ISSUE THREAD

**Issue by plumps** [Ovvovy/pytivity#1]
`pytivity create --started dolphin MyNewActivity`
```Traceback (most recent call last):
  File "/nix/store/q1zfy8hrsxfxqqypdshwyszi2vxaafxf-pytivity-v0.0.4/bin/.pytivity-wrapped", line 12, in <module>
    sys.exit(main())
  File "/nix/store/q1zfy8hrsxfxqqypdshwyszi2vxaafxf-pytivity-v0.0.4/lib/python3.5/site-packages/pytivity/cli.py", line 135, in main
    notification_bus=notification_bus)
  File "/nix/store/q1zfy8hrsxfxqqypdshwyszi2vxaafxf-pytivity-v0.0.4/lib/python3.5/site-packages/pytivity/cli.py", line 143, in create
    activity = KActivity.create(args.name, bus=activity_bus)
  File "/nix/store/q1zfy8hrsxfxqqypdshwyszi2vxaafxf-pytivity-v0.0.4/lib/python3.5/site-packages/pytivity/kactivity.py", line 291, in create
    activity._create_directory()
  File "/nix/store/q1zfy8hrsxfxqqypdshwyszi2vxaafxf-pytivity-v0.0.4/lib/python3.5/site-packages/pytivity/kactivity.py", line 220, in _create_directory
    os.mkdir(path + p)
FileNotFoundError: [Errno 2] No such file or directory: '/home/plumps/.local/share/kactivitymanagerd/activities/8bd794d1-cc56-48c7-aafb-c56f025d8cd1'
```

Creating the dir manually fixes the issue.
`mkdir ~/.local/share/kactivitymanagerd/activities`

**Comment by ovv** [comment]
Thanks for the report :+1:
